zf:
  build: .
  dockerfile: Dockerfile
  environment:
      XDEBUG_CONFIG: remote_host=192.168.1.23
  ports:
   - "127.0.0.33:80:80"
  volumes:
   - .:/var/www
  links:
    - database
database:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
     - MYSQL_USERNAME=root
     - MYSQL_ROOT_PASSWORD=123
     - MYSQL_DATABASE=blog
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=123
      - PMA_ARBITRARY=1
    ports:
      - "127.0.0.34:80:80"