<?php
$this->navigation('default')->menu()->setPartial('partials/menu');
?>
<?= $this->doctype() ?>

<html lang="pl">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Admin Panel')
        ->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink()
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/admin.css'))
    ?>

    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>
<nav class="nav">
    <?= $this->navigation()->menu()->render(); ?>
</nav>
<main class="main">
    <?= $this->content ?>
</main>
</body>
</html>
