<?php if ($this->posts): ?>
    <?php foreach ($this->posts as $post): ?>
        <a class="main__a" href="<?= $this->url('post', ['id' => $post->getId()]) ?>">
            <article class="main__a__div">
                <h2 class="main__a__div__h2"><?= $post->getTitle() ?></h2>
                <div class="main__a__div__div">
                    <?= $post->getDescription() ?>
                </div>
            </article>
        </a>
    <?php endforeach; ?>
<?php else: ?>
    Brak postów na stronie
<?php endif ?>
