<?php
/* @var $post \Blog\Entity\PostEntity */
$post = $this->post;
/* @var $tagsService \Blog\Service\TagsService\TagsServiceInterface */
$tagsService = $this->tagsService;
?>
<article class="main__a__div">
    <h2 class="main__a__div__h2"><?= $this->escapeHtml($post->getTitle()) ?></h2>
    <div class="main__a__div__div">
        <div class="author">Opublikowane przez <?= $this->escapeHtml($post->getUser()->getName()) ?> </div>
        <?=
        $tagsService->convert([
            '{POST_TITLE}' => $this->escapeHtml($post->getTitle())
        ], $post->getContent())
        ?>
    </div>
</article>